const characterNameList = [
  // AUTO-GENERATED-START
  "Unknown",
  "Belle",
  "Wise",
  "Anby",
  "Billy",
  "Nicole",
  "Nekomata",
  "Koleda",
  "Ben",
  "Grace",
  "Anton",
  "Lycaon",
  "Rina",
  "Corin",
  "Soldier11",
  "Soukaku",
  "Lucy",
  "Piper",
  "Ellen",
  "ZhuYuan",
  "Qingyi",
  "Jane",
  "Seith",
  "Caesar",
  "Burnice",
  "Yanagi",
  "Lighter",
  "Harumasa",
  "Miyabi",
  "Astra",
  "Evelyn",
  "Pulchra",
  "Anby0",
  "Trigger",
  "Hugo",
  "Vivian",
  "Yixuan",
  "PanYinhu",
  "JuFufu",
  "Yuzuha",
  "Alice",
  "Seed",
  "Orphie",
  "Lucia",
  "Manato",
  "Yidhari",
  "Dialyn",
  "Banyue",
  "Zhao",
  "YeShunguang",
  "Sunna",
  "Aria",
  "Nangong",
  "Cissia",
  // AUTO-GENERATED-END
] as const;

type Character = (typeof characterNameList)[number];

const characterGenderMap: Record<Character, string> = {
  // GENDER_MAP_START
  Unknown: "unknown" as const,
  Belle: "female" as const,
  Wise: "male" as const,
  Anby: "female" as const,
  Billy: "male" as const,
  Nicole: "female" as const,
  Nekomata: "female" as const,
  Koleda: "female" as const,
  Ben: "male" as const,
  Grace: "female" as const,
  Anton: "male" as const,
  Lycaon: "male" as const,
  Rina: "female" as const,
  Corin: "female" as const,
  Soldier11: "female" as const,
  Soukaku: "female" as const,
  Lucy: "female" as const,
  Piper: "female" as const,
  Ellen: "female" as const,
  ZhuYuan: "female" as const,
  Qingyi: "female" as const,
  Jane: "female" as const,
  Seith: "male" as const,
  Caesar: "female" as const,
  Burnice: "female" as const,
  Yanagi: "female" as const,
  Lighter: "male" as const,
  Harumasa: "male" as const,
  Miyabi: "female" as const,
  Astra: "female" as const,
  Evelyn: "female" as const,
  Pulchra: "female" as const,
  Anby0: "female" as const,
  Trigger: "female" as const,
  Hugo: "male" as const,
  Vivian: "female" as const,
  Yixuan: "female" as const,
  PanYinhu: "male" as const,
  JuFufu: "female" as const,
  Yuzuha: "female" as const,
  Alice: "female" as const,
  Seed: "female" as const,
  Orphie: "female" as const,
  Lucia: "female" as const,
  Manato: "male" as const,
  Yidhari: "female" as const,
  Dialyn: "female" as const,
  Banyue: "male" as const,
  Zhao: "female" as const,
  YeShunguang: "female" as const,
  Sunna: "female" as const,
  Aria: "female" as const,
  Nangong: "female" as const,
  Cissia: "female" as const,
  // GENDER_MAP_END
};

export { characterNameList, characterGenderMap };
export type { Character };
