; Sunna

; Constants -------------------------

[Constants]
global $active = 0
global $creditinfo = 0

global persist $upper = 2
global persist $bra = 2
global persist $nips = 0

global persist $foot = 0
global persist $panties = 2
global persist $belt = 1

global persist $backpack = 1
global persist $shorts = 1

global persist $line = 1
global persist $eyewear = 0
global persist $ballgag = 0
global persist $face = 0
global persist $oil = 0

[KeyUpper]
condition = $active == 1
key = no_modifiers UP
type = cycle
$upper = 1,2,3,0,4

[KeyBra]
condition = $active == 1
key = ctrl UP
type = cycle
$bra = 0,1,2,3

[KeyNips]
condition = $active == 1
key = alt UP
type = cycle
$nips = 0,1,2

[KeyFoot]
condition = $active == 1
key = no_modifiers DOWN
type = cycle
$foot = 0,1,2

[KeyPanties]
condition = $active == 1
key = ctrl DOWN
type = cycle
$panties = 0,1,2,3

[KeyBelt]
condition = $active == 1
key = alt DOWN
type = cycle
$belt = 0,1

[KeyBackpack]
condition = $active == 1
key = LEFT
type = cycle
$backpack = 0,1

[KeyShorts]
condition = $active == 1
key = RIGHT
type = cycle
$shorts = 0,1

[KeyToyLine]
condition = $active == 1
key = 6
type = cycle
$line = 0,1

[KeyEyewear]
condition = $active == 1
key = 7
type = cycle
$eyewear = 0,1,2

[KeyBallGag]
condition = $active == 1
key = 8
type = cycle
$ballgag = 0,1

[KeyFace]
condition = $active == 1
key = 9
type = cycle
$face = 0,1,2

[KeyOilSkin]
condition = $active == 1
key = 0
type = cycle
$oil = 0,1

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides -------------------------

[TextureOverrideSunnaCharmIB]
hash = 337a62c1
match_priority = 0
if $active == 1 && $backpack == 0
	ib = null
endif

[TextureOverrideSunnaFaceIB]
hash = 1a2c8573
match_priority = 0
if $active == 1
	if $face == 1
		Resource\ZZMI\Diffuse = ref ResourceSunnaFaceADiffuse1
		run = CommandList\ZZMI\SetTextures
	elif $face == 2
		Resource\ZZMI\Diffuse = ref ResourceSunnaFaceADiffuse2
		run = CommandList\ZZMI\SetTextures
	endif
endif

[TextureOverrideSunnaHairBlend]
hash = 0c183c3f
handling = skip
vb2 = ResourceSunnaHairBlend
if DRAW_TYPE == 1
	vb0 = ResourceSunnaHairPosition
	draw = 8762, 0
endif

[TextureOverrideSunnaHairTexcoord]
hash = 06bea24e
vb1 = ResourceSunnaHairTexcoord

[TextureOverrideSunnaHairVertexLimitRaise]
hash = cc070c66
override_vertex_count = 8762
override_byte_stride = 40

[TextureOverrideSunnaBodyBlend]
hash = 53661c9a
handling = skip
vb2 = ResourceSunnaBodyBlend
if DRAW_TYPE == 1
	vb0 = ResourceSunnaBodyPosition
	draw = 76175, 0

	$active = 1
endif

[TextureOverrideSunnaBodyTexcoord]
hash = 712eb020
vb1 = ResourceSunnaBodyTexcoord

[TextureOverrideSunnaBodyVertexLimitRaise]
hash = 8991360f
override_vertex_count = 76175
override_byte_stride = 40

[TextureOverrideSunnaHairIB]
hash = 904ecd0f
handling = skip

[TextureOverrideSunnaHairA]
hash = 904ecd0f
match_first_index = 0
ib = ResourceSunnaHairAIB
; Resource\ZZMI\Diffuse = ref ResourceSunnaHairADiffuse
; Resource\ZZMI\NormalMap = ref ResourceSunnaHairANormalMap
; Resource\ZZMI\LightMap = ref ResourceSunnaHairALightMap
; Resource\ZZMI\MaterialMap = ref ResourceSunnaHairAMaterialMap
; Resource\ZZMI\WengineFX = ref ResourceSunnaHairAWengineFX
; run = CommandList\ZZMI\SetTextures
; HairA (5306)
drawindexed = 20544, 0, 0
if $shorts == 1
	; 短裤 (1741)
	drawindexed = 6090, 20544, 0
endif

[TextureOverrideSunnaHairB]
hash = 904ecd0f
match_first_index = 26520
ib = ResourceSunnaHairBIB
; run = CommandList\ZZMI\SetTextures
; HairB (1715)
drawindexed = 5847, 0, 0

[TextureOverrideSunnaBodyIB]
hash = b3c6ea5a
handling = skip

[TextureOverrideSunnaBodyA]
hash = b3c6ea5a
match_first_index = 0
ib = ResourceSunnaBodyAIB
Resource\ZZMI\Diffuse = ref ResourceSunnaBodyADiffuse
Resource\ZZMI\NormalMap = ref ResourceSunnaBodyANormalMap
if $oil == 0
	Resource\ZZMI\LightMap = ref ResourceSunnaBodyALightMap
else
	Resource\ZZMI\LightMap = ref ResourceSunnaBodyALightMap1
endif
Resource\ZZMI\MaterialMap = ref ResourceSunnaBodyAMaterialMap
Resource\ZZMI\WengineFX = ref ResourceSunnaBodyAWengineFX
run = CommandList\ZZMI\SetTextures
; Base
; 上半身 (5379)
drawindexed = 28596, 0, 0
; 下半身 (7996)
drawindexed = 42375, 28596, 0
if $shorts == 0
	; 下半身+ (422)
	drawindexed = 1962, 70971, 0
endif
; 手臂 (3174)
drawindexed = 13236, 72933, 0
; 脖子 (554)
drawindexed = 1896, 86169, 0

; Nips
if $upper != 1 && $bra == 0
	if $nips == 1
		; Nips1 (544)
		drawindexed = 2802, 88065, 0
	elif $nips == 2
		; Nips2 (2924)
		drawindexed = 15510, 90867, 0
	endif
endif

; Foot
if $foot == 1
	; 凉鞋 (7069)
	drawindexed = 34044, 106377, 0
elif $foot == 0
	; 原版鞋 (1438)
	drawindexed = 5688, 140421, 0
elif $foot == 2
	; 果足 (4630)
	drawindexed = 24804, 146109, 0
endif

; Panties
if $panties == 1
	; 拘束内裤 (2206)
	drawindexed = 9474, 170913, 0
elif $panties == 2
	; 粉白内裤 (610)
	drawindexed = 1806, 180387, 0
endif

; Cloth
if $upper != 1 && $bra == 1
	; 拘束内衣 (3196)
	drawindexed = 17058, 182193, 0
endif
if $upper == 4
	; 拘束带 (11077)
	drawindexed = 47502, 199251, 0
endif
if $upper != 1 && $bra == 2
	; 比基尼 (2315)
	drawindexed = 11781, 246753, 0
endif
if $upper != 1 && $bra == 3
	; 爱心乳贴 (578)
	drawindexed = 3072, 258534, 0
endif
if $upper == 1
	; 衬衫 (4906)
	drawindexed = 22200, 261606, 0
elif $upper == 2
	; 衬衫半开 (5028)
	drawindexed = 22485, 283806, 0
endif

; Accs
if $upper == 3
	; 0领带 (300)
	drawindexed = 780, 306291, 0
endif
if $upper != 1 && $upper != 2 && $belt == 1
	; 1腰带 (514)
	drawindexed = 1836, 307071, 0
endif
if $backpack == 1
	; 2背包 (4095)
	drawindexed = 10830, 308907, 0
endif
if $eyewear == 1
	; 3眼罩 (2674)
	drawindexed = 13290, 319737, 0
endif
if $ballgag == 1
	; 4口球 (2216)
	drawindexed = 6960, 333027, 0
endif
if $eyewear == 2
	; 5马赛克眼镜 (1534)
	drawindexed = 1920, 339987, 0
endif
if $line == 1
	; 6线 (507)
	drawindexed = 2736, 341907, 0
endif
if $panties == 3
	; 7贴 (289)
	drawindexed = 1536, 344643, 0
endif

[TextureOverrideSunnaScreenVB0]
hash = dd676093
if $active == 1 && $upper != 1 && $upper != 2 && $belt == 0
	handling = skip
endif

; CommandList -----------------------

[CommandListCreditInfo]
if $creditinfo == 0 && $active > 0
	pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
	pre run = CustomShader\ShaderFixes\help.ini\FormatText
	pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
	$creditinfo = 1
endif

; Resources -------------------------

[ResourceSunnaHairPosition]
type = Buffer
stride = 40
filename = SunnaHairPosition.buf

[ResourceSunnaHairBlend]
type = Buffer
stride = 32
filename = SunnaHairBlend.buf

[ResourceSunnaHairTexcoord]
type = Buffer
stride = 20
filename = SunnaHairTexcoord.buf

[ResourceSunnaHairAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SunnaHairA.ib

[ResourceSunnaHairBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SunnaHairB.ib

[ResourceSunnaBodyPosition]
type = Buffer
stride = 40
filename = SunnaBodyPosition.buf

[ResourceSunnaBodyBlend]
type = Buffer
stride = 32
filename = SunnaBodyBlend.buf

[ResourceSunnaBodyTexcoord]
type = Buffer
stride = 24
filename = SunnaBodyTexcoord.buf

[ResourceSunnaBodyAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SunnaBodyA.ib

[ResourceSunnaPhotoPosition]
type = Buffer
stride = 40
filename = SunnaPhotoPosition.buf

[ResourceSunnaPhotoBlend]
type = Buffer
stride = 4
filename = SunnaPhotoBlend.buf

[ResourceSunnaPhotoTexcoord]
type = Buffer
stride = 28
filename = SunnaPhotoTexcoord.buf

[ResourceSunnaPhotoAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SunnaPhotoA.ib

; [ResourceSunnaHairADiffuse]
; filename = SunnaHairADiffuse.dds

; [ResourceSunnaHairANormalMap]
; filename = SunnaHairANormalMap.dds

; [ResourceSunnaHairALightMap]
; filename = SunnaHairALightMap.dds

; [ResourceSunnaHairAMaterialMap]
; filename = SunnaHairAMaterialMap.dds

; [ResourceSunnaHairAWengineFX]
; filename = SunnaHairAWengineFX.dds

[ResourceSunnaBodyADiffuse]
filename = SunnaBodyADiffuse.dds

[ResourceSunnaBodyANormalMap]
filename = SunnaBodyANormalMap.dds

[ResourceSunnaBodyALightMap]
filename = SunnaBodyALightMap.dds

[ResourceSunnaBodyALightMap1]
filename = SunnaBodyALightMap1.dds

[ResourceSunnaBodyAMaterialMap]
filename = SunnaBodyAMaterialMap.dds

[ResourceSunnaBodyAWengineFX]
filename = SunnaBodyAWengineFX.dds

[ResourceSunnaFaceADiffuse1]
filename = SunnaFaceADiffuse1.dds

[ResourceSunnaFaceADiffuse2]
filename = SunnaFaceADiffuse2.dds

[ResourceCreditInfo]
type = Buffer
data = "Created by HammyCatte"

[Constants]
global $help = 0
[KeyHelp]
condition = $active == 1
key = CTRL ALT
type = cycle
$help = 0,1
[Present]
if $help == 1 && $active == 1
	run = CommandListHelp
else
	run = CommandListClean
endif
[CommandListHelp]
pre Resource\ShaderFixes\help.ini\Help = ref ResourceHelp
[CommandListClean]
post Resource\ShaderFixes\help.ini\Help = null
[ResourceHelp]
type = buffer
format = R8_UINT
filename = SunnaHelpText.buf

; .ini generated by XXMI (XX-Model-Importer) v1.5.8
; If you have any issues or find any bugs, please open a ticket at https://github.com/leotorrez/XXMI-Tools/issues
