import fs from "fs-extra";
import path from "path";
import { fileURLToPath } from "url";
import { format, resolveConfig } from "prettier";

// Define paths
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");

const charactersJsonPath = path.join(__dirname, "characters.json");
const characterTsPath = path.join(rootDir, "src", "shared", "character.ts");
const characterOutfitsPath = path.join(rootDir, "src", "shared", "characterOutfits.ts");
const enJsonPath = path.join(rootDir, "src", "renderer", "src", "i18n", "locales", "en.json");
const zhJsonPath = path.join(rootDir, "src", "renderer", "src", "i18n", "locales", "zh.json");

// Define types
interface CharacterData {
  id: string;
  nicknames: { en: string; zh: string };
  fullnames: { en: string; zh: string };
  // Index 0 is the default outfit. Append new outfits; existing indices are saved in modinfo.json.
  outfits?: { en: string; zh: string }[];
}

async function main() {
  try {
    // Read characters.json
    console.log(`Reading characters from ${charactersJsonPath}...`);
    if (!(await fs.pathExists(charactersJsonPath))) {
      throw new Error(`${charactersJsonPath} not found.`);
    }
    const characters: CharacterData[] = await fs.readJson(charactersJsonPath);

    for (const character of characters) {
      if (
        character.outfits !== undefined &&
        (!Array.isArray(character.outfits) ||
          character.outfits.some((outfit) => !outfit?.en?.trim() || !outfit?.zh?.trim()))
      ) {
        throw new Error(`Invalid outfits for ${character.id}: each outfit needs English and Chinese names.`);
      }
    }

    // 1. Update character.ts
    console.log(`Updating ${characterTsPath}...`);
    if (await fs.pathExists(characterTsPath)) {
      const characterTsContent = await fs.readFile(characterTsPath, "utf-8");
      const characterListString = characters.map((c) => `  "${c.id}",`).join("\n");

      const markerRegex = /(\/\/ AUTO-GENERATED-START)[\s\S]*?(\/\/ AUTO-GENERATED-END)/;

      if (markerRegex.test(characterTsContent)) {
        const newCharacterTsContent = characterTsContent.replace(markerRegex, `$1\n${characterListString}\n  $2`);
        await fs.writeFile(characterTsPath, newCharacterTsContent, "utf-8");
      } else {
        console.error(`Error: Could not find AUTO-GENERATED markers in ${characterTsPath}`);
      }
    } else {
      console.error(`Error: ${characterTsPath} not found.`);
    }

    // Outfit IDs are array indices. Characters without a list still have outfit 0.
    const outfitCounts = characters.map((c) => `  ${JSON.stringify(c.id)}: ${Math.max(1, c.outfits?.length ?? 0)},`);
    await fs.writeFile(
      characterOutfitsPath,
      await format(
        [
          "// AUTO-GENERATED by npm run gen:characters. Do not edit manually.",
          'import type { Character } from "./character";',
          "",
          "export const characterOutfitCounts: Record<Character, number> = {",
          ...outfitCounts,
          "};",
          "",
        ].join("\n"),
        { ...(await resolveConfig(characterOutfitsPath)), parser: "typescript" }
      ),
      "utf-8"
    );

    // 2. Update i18n files
    const updateI18nFile = async (filePath: string, lang: "en" | "zh") => {
      console.log(`Updating ${filePath}...`);
      if (!(await fs.pathExists(filePath))) {
        console.error(`Error: ${filePath} not found.`);
        return;
      }

      const content = await fs.readJson(filePath);

      // Ensure structure exists
      content.characters = content.characters || {};

      // Clear existing values to handle deletions
      content.characters.nicknames = {};
      content.characters.fullnames = {};
      content.characters.outfits = {};

      // Update values
      characters.forEach((c) => {
        content.characters.nicknames[c.id] = c.nicknames[lang];
        content.characters.fullnames[c.id] = c.fullnames[lang];
        const outfits = c.outfits?.length ? c.outfits : [{ en: "Default Outfit", zh: "默认时装" }];
        content.characters.outfits[c.id] = Object.fromEntries(outfits.map((outfit, id) => [id, outfit[lang]]));
      });

      await fs.writeJson(filePath, content, { spaces: 2 });
    };

    await updateI18nFile(enJsonPath, "en");
    await updateI18nFile(zhJsonPath, "zh");

    console.log("Character generation complete.");
  } catch (error) {
    console.error("An error occurred:", error);
    process.exit(1);
  }
}

main();
